// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

import com.fasterxml.jackson.databind.deser.std.StdScalarDeserializer;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    /**
     * public static final class DriveConstants {
     * public static final int kLeftMotor1Port = 0;
     * public static final int kLeftMotor2Port = 1;
     * public static final int kRightMotor1Port = 2;
     * public static final int kRightMotor2Port = 3;
     * }
     */

    // Shooter Constants
    public static final int defaultMainShooterSpeed = 1700; 
    public static final int defaultSecondaryShooterSpeed = 2300;
    public static final int shooterEncoderPulses = 2048;

    public static final double hoodP = 0;
    public static final double hoodI = 0;
    public static final double hoodD = 0;

    public static final double hoodEncoderOffset = 0;
    //the tooth to tooth of the hood
    public static final double hoodAngleRatio = 34.000 / 536.000;
    //the max and min of the hood angle not the encoder values
    public static final double minHoodPosition = .5;
    public static final double maxHoodPosition = 20.0;

}
