// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

// import org.ejml.FancyPrint;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean
 * constants. This class should not be used for any other purpose. All constants
 * should be
 * declared globally (i.e. public static). Do not put anything functional in
 * this class.
 *
 * <p>
 * It is advised to statically import this class (or one of its inner classes)
 * wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    /**
     * public static final class DriveConstants {
     * public static final int kLeftMotor1Port = 0;
     * public static final int kLeftMotor2Port = 1;
     * public static final int kRightMotor1Port = 2;
     * public static final int kRightMotor2Port = 3;
     * }
     */

    // Shooter Constants
    public static final int defaultMainShooterSpeed = 1700; 
    public static final int defaultSecondaryShooterSpeed = 2300;
    public static final int shooterEncoderPulses = 2048;

    //Intake Constant
    public static final double defaultInatkeSpeed = 0.5;

    //Turret Constants
    public static final double turretP = 0.062;
    public static final double turretI = 0.0;
    public static final double turretD = 0.003;
    public static final double turretTolerance = 0.5;
    public static final int turretOffset = 2074;
    public static final int turretMinEnd = 20;
    public static final int turretMaxEnd = 340;
    public static final int turretMaxSlowZone = 300;
    public static final int turretMinSlowZone = 60;

    // Vision Constants
    public static final double cameraAngle = 0;
    public static final double cameraHeight = 0;
    public static final double goalHeight = 103;
    public static final double hoodP = 0;
    public static final double hoodI = 0;
    public static final double hoodD = 0;

    public static final double hoodEncoderOffset = -315.0;
    
    //the tooth to tooth of the hood
    public static final double hoodAngleRatio = 34.000 / 536.000;
    //the max and min of the hood angle not the encoder values
    public static final double minHoodPosition = 360.0;
    public static final double minHoodPositionOverlap = 340.0;

    public static final double maxHoodPosition = 295.0;
    public static final double maxHoodPositionOverlap = 315.0;
    // public static final double maxHoodPositionOverlap = 0;

}
